#!/usr/bin/perl -w

use strict;

use Time::HiRes qw(time);

use Cwd;

my $dir = getcwd;

my $whiskerdir = $dir . q{/../../../tcp/remy/rats/new/};

for my $nsrc ( 8 ) { # maximum degree of multiplexing
    system qq{python runremy.py -c remyconf/dumbbell-buf25-rtt150-bneck15.tcl -d results/Dumbbell -p TCP/Newreno -n $nsrc &};
    system qq{python runremy.py -c remyconf/dumbbell-buf25-rtt150-bneck15.tcl -d results/Dumbbell -p TCP/Linux/cubic -n $nsrc &};
    system qq{python runremy.py -c remyconf/dumbbell-buf25-rtt150-bneck15.tcl -d results/Dumbbell -p TCP/Linux/compound -n $nsrc &};
    # system qq{python runremy.py -c remyconf/dumbbell-buf250-rtt150-bneck15.tcl -d results/Dumbbell -p TCP/Vegas -n $nsrc &};

    # system qq{python runremy.py -c remyconf/dumbbell-buf250-rtt150-bneck15.tcl -d results/Dumbbell  -p TCP/Reno/XCP -n $nsrc &};
    # system qq{python runremy.py -c remyconf/dumbbell-buf250-rtt150-bneck15.tcl -d results/Dumbbell  -p Cubic/sfqCoDel -n $nsrc &};

    $ENV{'WHISKERS'} = $whiskerdir . q{delta0.1.dna};
    system qq{python runremy.py -c remyconf/dumbbell-buf25-rtt150-bneck15.tcl -d results/Dumbbell-rational-delta0.1 -p TCP/Rational -n $nsrc &};

    $ENV{'WHISKERS'} = $whiskerdir . q{delta1.dna};
    system qq{python runremy.py -c remyconf/dumbbell-buf25-rtt150-bneck15.tcl -d results/Dumbbell-rational-delta1 -p TCP/Rational -n $nsrc &};

    $ENV{'WHISKERS'} = $whiskerdir . q{delta10.dna};
    system qq{python runremy.py -c remyconf/dumbbell-buf25-rtt150-bneck15.tcl -d results/Dumbbell-rational-delta10 -p TCP/Rational -n $nsrc &};

    $ENV{'WHISKERS'} = "8"
    $ENV{'rtt'} = "150"
    my $t = time;
    system qq{checkpoints=stored_checkpoints/1_${t} delay_delta=1 python runremy.py -c remyconf/dumbbell-buf25-rtt150-bneck15.tcl -d results/Dumbbell-1 -p TCP/Unicorn -n $nsrc &};

    sleep(1); my $t = time;
    system qq{checkpoints=stored_checkpoints/2_${t} delay_delta=2 python runremy.py -c remyconf/dumbbell-buf25-rtt150-bneck15.tcl -d results/Dumbbell-2 -p TCP/Unicorn -n $nsrc &};
}
